import Head from "next/head";
import Image from "next/image";
import estilos from "@/styles/Home.module.css";
import Topo from '@/componentes/topo/index.jsx'
import Capa from '@/componentes/secao-capa/index.jsx'
import Produtos from "@/componentes/secao-produtos";
import Sobre from "@/componentes/secao-sobre/index.jsx";
import Contato from "@/componentes/secao-contato/index.jsx";
import Rodape from "@/componentes/rodape/index.jsx";
import { SpeedInsights } from "@vercel/speed-insights/next"


export default function Home() {
  return (
    <>
      <Head>
        <title>Óticas Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SpeedInsights /> 
      <Topo />
      <Capa />
      <Produtos />
      <Sobre />
      <Contato />
      <Rodape />
    </>
  );
}
